# Generated by Django 3.1.13 on 2021-07-13 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210713_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 3, 29, 56, 364781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='verification_code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
