# Generated by Django 3.1.13 on 2021-07-17 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210716_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 19, 51, 53, 616452, tzinfo=utc)),
        ),
    ]
