# Generated by Django 3.1.13 on 2021-07-18 00:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210718_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='password_reset_link',
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 0, 59, 58, 417074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 0, 59, 58, 416135, tzinfo=utc)),
        ),
    ]
