# Generated by Django 3.1.13 on 2021-07-18 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210718_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 15, 21, 18, 963098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 15, 21, 18, 962204, tzinfo=utc)),
        ),
    ]
