# Generated by Django 3.1.13 on 2021-07-18 23:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210718_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
