# Generated by Django 3.1.13 on 2021-07-18 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210718_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 16, 25, 43, 297371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 16, 25, 43, 296598, tzinfo=utc)),
        ),
    ]
