# Generated by Django 3.1.13 on 2021-07-18 16:36

import datetime
import django.contrib.auth.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210718_1625'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 16, 36, 32, 80898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 16, 36, 32, 80121, tzinfo=utc)),
        ),
    ]
