# Generated by Django 3.1.13 on 2021-07-21 23:17

import blog_api.users.model_validators
import datetime
import django.contrib.auth.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210721_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator, blog_api.users.model_validators.validate_min_3_characters, blog_api.users.model_validators.validate_3_special_characters_max]),
        ),
    ]
