# Generated by Django 3.1.13 on 2021-07-30 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210729_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
