# Generated by Django 3.1.13 on 2021-07-29 23:56

import blog_api.posts.validators
import blog_api.users.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210728_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=30, unique=True, validators=[blog_api.users.model_validators.validate_no_special_chars, blog_api.users.model_validators.validate_min_3_characters])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[blog_api.posts.validators.validate_min_8_words]),
        ),
    ]
