# Generated by Django 3.1.13 on 2021-07-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='pub_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
