# Generated by Django 3.1.13 on 2021-07-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_tag_pub_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='post_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
