# Generated by Django 3.1.13 on 2021-08-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210730_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
    ]
