# Generated by Django 3.1.13 on 2021-08-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post_count',
        ),
    ]
